apiVersion: v1
kind: PersistentVolume
metadata:
  name: ppvol-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/sfw
    server: cp
    readOnly: false