apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /etc/cars
          name: car-vol
      # kubectl exec -ti shell-demo -- cat /etc/cars/car.model
  volumes:
    - name: car-vol
      configMap:
        name: fast-car