apiVersion: batch/v1
kind: Job
metadata:
  name: sleepy
spec:
  template:
    spec:
      containers:
        - name: resting
          image: busybox
          command: [ "/bin/sleep" ]
          args: [ "5" ]
      restartPolicy: Never
  backoffLimit: 1
  completions: 5
  parallelism: 2
  activeDeadlineSeconds: 15