apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sample-crd
rules:
- apiGroups:
  - sgerard.be
  resources:
  - backups
  verbs:
  - list
  - watch
  - get
- apiGroups: [""]
  resources:
    - endpoints
  verbs:
    - list
    - watch
    - get
    - create
    - update
