apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: annotation-operator
rules:
  - apiGroups:
      - sgerard.be
    resources:
      - annotations
    verbs: [ "list","get", "watch", "create","update","patch","delete" ]
  - apiGroups: [ "" ]
    resources: [ "endpoints" ]
    verbs: [ "list","get", "watch", "create","update","patch","delete" ]
  - apiGroups: [ "", "extensions","apps" ]
    resources: [ "deployments", "replicasets", "pods" ]
    verbs: [ "list","get", "watch", "create","update","patch","delete" ]

# kubectl auth can-i --as=system:serviceaccount:annotation-operator:annotation-operator --list