apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: annotations.sgerard.be
spec:
  group: sgerard.be
  scope: Cluster
  names:
    kind: Annotation
    singular: annotation
    plural: annotations
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: This resource contains a "spec" fields defining the operator configuration.
          properties:
            spec:
              type: object
              properties:
                annotations:
                  type: object
                  additionalProperties:
                    type: string