apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: annotation-operator
  name: annotation-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: annotation-operator
  strategy: {}
  template:
    metadata:
      labels:
        app: annotation-operator
    spec:
      containers:
      - image: docker.io/sebge2/sample-crd:1.0.0-SNAPSHOT
        name: annotation-operator
        imagePullPolicy: Always
      serviceAccountName: annotation-operator
