apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backups.sgerard.be
spec:
  group: sgerard.be
  scope: Cluster
  names:
    kind: Backup
    singular: backup
    plural: backups
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: This resource contains a "spec" fields defining the operator configuration.
          properties:
            spec:
              type: object
              properties:
                namespaces:
                  type: array
                  items:
                    type: string