kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: production
  namespace: production
subjects:
  - kind: User
    name: toto
    apiGroup: ""
roleRef:
  kind: Role
  name: developer-prod
  apiGroup: ""
