kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: development
  namespace: development
subjects:
  - kind: User
    name: toto
    apiGroup: ""
roleRef:
  kind: Role
  name: developer
  apiGroup: ""
