apiVersion: apps/v1
kind: Deployment
metadata:
  name: anti-affinity-2
spec:
  replicas: 10
  selector:
    matchLabels:
      app: anti-affinity-2
  template:
    metadata:
      labels:
        app: anti-affinity-2
    spec:
      containers:
        - name:  nginx
          image: nginx:1.20.1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - anti-affinity-1
            topologyKey: kubernetes.io/hostname