#kubectl label nodes [NODE] kubernetes.io/role=worker
#kubectl label nodes [NODE] topology.kubernetes.io=zone-eu
#kubectl label nodes [NODE] topology.kubernetes.io=zone-us
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anti-affinity-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anti-affinity-1
  template:
    metadata:
      labels:
        app: anti-affinity-1
    spec:
      containers:
        - name:  nginx
          image: nginx:1.20.1
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - anti-affinity-2
            topologyKey: kubernetes.io/hostname