apiVersion: v1
kind: Pod
metadata:
  name: pod-with-json-secret-as-volume
spec:
  containers:
    - name: nginx
      image: nginx:1.15.1
      volumeMounts:
        - mountPath: /etc/my-secret
          name: my-secret-volume
          # kubectl exec -ti pod-with-json-secret-as-volume -- cat /etc/my-secret/config_first.json
  volumes:
    - name: my-secret-volume
      configMap:
        name: my-config-with-inline-json