apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret-as-volume
spec:
  containers:
    - name: nginx
      image: nginx:1.15.1
      volumeMounts:
        - mountPath: /etc/my-secret
          name: my-secret-volume
          # kubectl exec -ti pod-with-secret-as-volume -- cat /etc/my-secret/password
  volumes:
    - name: my-secret-volume
      secret:
        secretName: my-secret