apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
spec:
  containers:
    - name: nginx
      image: nginx:1.15.1
      env:
        #  kkubectl exec -ti pod-with-secret -- env
        - name: MY_ENV
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password